"use client";
import InvoiceModal from "@/components/modal/InvoiceModal";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ApolloProvider } from "@apollo/client";
import client from "@/graphql/apollo-client";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={poppins.className}>
                <ApolloProvider client={client}>
                    <InvoiceModal />
                    {children}
                </ApolloProvider>
            </body>
        </html>
    );
}
